# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: aredoko_user
  password: aredoko_pass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aredoko_db

test:
  <<: *default
  database: aredoko_test

production:
  <<: *default
  database: aredoko_prod
  username: aredoko_user
  password: <%= ENV['ARE_DOKO_DATABASE_PASSWORD'] %>