services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3001:3001"
    command: rails server -b 0.0.0.0 -p 3001
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aredoko_user
      POSTGRES_PASSWORD: aredoko_pass
      POSTGRES_DB: aredoko_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  pgdata: